#!/usr/bin/env bash
# my-attribution — API client | Generated by Sheept 🐑 skillify
set -euo pipefail
API_KEY="${MY_ATTRIBUTION_API_KEY:-}"
BASE_URL="${MY_ATTRIBUTION_URL:-https://my-attribution.shpt.ai}"
AUTH_HEADER="${MY_ATTRIBUTION_AUTH_HEADER:-Authorization}"
AUTH_PREFIX="${MY_ATTRIBUTION_AUTH_PREFIX:-Bearer }"
[ -z "$API_KEY" ] && { echo "Error: MY_ATTRIBUTION_API_KEY not set. export MY_ATTRIBUTION_API_KEY=your-key" >&2; exit 1; }
handle_response() {
  local input; input=$(cat); local http_code; http_code=$(echo "$input" | tail -1)
  local body; body=$(echo "$input" | sed '$d')
  case "$http_code" in
    2[0-9][0-9]) echo "$body" | python3 -c "import sys,json; print(json.dumps(json.load(sys.stdin),indent=2))" 2>/dev/null || echo "$body" ;;
    401) echo "Error: Unauthorized — check MY_ATTRIBUTION_API_KEY" >&2; exit 1 ;;
    403) echo "Error: Forbidden" >&2; exit 1 ;; 404) echo "Error: Not found" >&2; exit 1 ;;
    422) echo "Error: Validation failed" >&2; echo "$body" >&2; exit 1 ;;
    429) echo "Error: Rate limited" >&2; exit 1 ;;
    5[0-9][0-9]) echo "Error: Server error (HTTP $http_code)" >&2; exit 1 ;;
    *) echo "Error: HTTP $http_code" >&2; echo "$body" >&2; exit 1 ;;
  esac
}
CMD="${1:-help}"
case "$CMD" in
  root)
    curl -s -w "\n%{http_code}" -X GET "${BASE_URL}/" \
      -H "${AUTH_HEADER}: ${AUTH_PREFIX}${API_KEY}" \
      -H "Content-Type: application/json" | handle_response
    ;;
  health)
    curl -s -w "\n%{http_code}" -X GET "${BASE_URL}/v1/health" \
      -H "${AUTH_HEADER}: ${AUTH_PREFIX}${API_KEY}" \
      -H "Content-Type: application/json" | handle_response
    ;;
  create-session)
    BODY="${2:-'{}'}"
    if [ "$BODY" = "{}" ] && [ "POST" = "POST" ]; then
      echo "Warning: sending empty body for POST request" >&2
    fi
    curl -s -w "\n%{http_code}" -X POST "${BASE_URL}/v1/sessions" \
      -H "${AUTH_HEADER}: ${AUTH_PREFIX}${API_KEY}" \
      -H "Content-Type: application/json" \
      -d "$BODY" | handle_response
    ;;
  list-sessions)
    curl -s -w "\n%{http_code}" -X GET "${BASE_URL}/v1/sessions" \
      -H "${AUTH_HEADER}: ${AUTH_PREFIX}${API_KEY}" \
      -H "Content-Type: application/json" | handle_response
    ;;
  create-advertiser)
    BODY="${2:-'{}'}"
    if [ "$BODY" = "{}" ] && [ "POST" = "POST" ]; then
      echo "Warning: sending empty body for POST request" >&2
    fi
    curl -s -w "\n%{http_code}" -X POST "${BASE_URL}/v1/advertisers" \
      -H "${AUTH_HEADER}: ${AUTH_PREFIX}${API_KEY}" \
      -H "Content-Type: application/json" \
      -d "$BODY" | handle_response
    ;;
  list-advertisers)
    curl -s -w "\n%{http_code}" -X GET "${BASE_URL}/v1/advertisers" \
      -H "${AUTH_HEADER}: ${AUTH_PREFIX}${API_KEY}" \
      -H "Content-Type: application/json" | handle_response
    ;;
  create-conversion)
    BODY="${2:-'{}'}"
    if [ "$BODY" = "{}" ] && [ "POST" = "POST" ]; then
      echo "Warning: sending empty body for POST request" >&2
    fi
    curl -s -w "\n%{http_code}" -X POST "${BASE_URL}/v1/conversions" \
      -H "${AUTH_HEADER}: ${AUTH_PREFIX}${API_KEY}" \
      -H "Content-Type: application/json" \
      -d "$BODY" | handle_response
    ;;
  advertiser-report)
    if [ -z "${2:-}" ]; then
      echo "Error: missing required argument <advertiser_id>" >&2
      echo "Usage: my-attribution.sh advertiser-report <advertiser_id>" >&2
      exit 1
    fi
    curl -s -w "\n%{http_code}" -X GET "${BASE_URL}/v1/reports/${2}" \
      -H "${AUTH_HEADER}: ${AUTH_PREFIX}${API_KEY}" \
      -H "Content-Type: application/json" | handle_response
    ;;
  advertiser-conversions)
    if [ -z "${2:-}" ]; then
      echo "Error: missing required argument <advertiser_id>" >&2
      echo "Usage: my-attribution.sh advertiser-conversions <advertiser_id>" >&2
      exit 1
    fi
    curl -s -w "\n%{http_code}" -X GET "${BASE_URL}/v1/reports/${2}/conversions" \
      -H "${AUTH_HEADER}: ${AUTH_PREFIX}${API_KEY}" \
      -H "Content-Type: application/json" | handle_response
    ;;
  global-stats)
    curl -s -w "\n%{http_code}" -X GET "${BASE_URL}/v1/stats" \
      -H "${AUTH_HEADER}: ${AUTH_PREFIX}${API_KEY}" \
      -H "Content-Type: application/json" | handle_response
    ;;
  help|--help|-h)
    echo "my-attribution — API client"
    echo "Usage: my-attribution.sh <command> [args...] [json-body]"
    echo "Commands:"
  echo "  root                                GET /"
  echo "  health                              GET /v1/health"
  echo "  create-session [json-body]          POST /v1/sessions"
  echo "  list-sessions                       GET /v1/sessions"
  echo "  create-advertiser [json-body]       POST /v1/advertisers"
  echo "  list-advertisers                    GET /v1/advertisers"
  echo "  create-conversion [json-body]       POST /v1/conversions"
  echo "  advertiser-report <advertiser_id>   GET /v1/reports/{advertiser_id}"
  echo "  advertiser-conversions <advertiser_id> GET /v1/reports/{advertiser_id}/conversions"
  echo "  global-stats                        GET /v1/stats"
    echo "Examples:"
    echo "  my-attribution.sh root"
    echo "Env: MY_ATTRIBUTION_API_KEY (key), MY_ATTRIBUTION_URL (url), MY_ATTRIBUTION_AUTH_HEADER (header), MY_ATTRIBUTION_AUTH_PREFIX (prefix)"
    ;;
  *)
    echo "Unknown command: $CMD — run 'my-attribution.sh --help'" >&2; exit 1 ;;
esac
